--- apps/desktop/desktop_native/chromium_importer/Cargo.toml.orig	2025-12-11 21:15:41 UTC
+++ apps/desktop/desktop_native/chromium_importer/Cargo.toml
@@ -34,7 +34,7 @@ tracing = { workspace = true }
 tokio = { workspace = true, features = ["full"] }
 tracing = { workspace = true }
 
-[target.'cfg(target_os = "linux")'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 cbc = { workspace = true, features = ["alloc"] }
 oo7 = { workspace = true }
 pbkdf2 = "=0.12.2"
