--- apps/desktop/desktop_native/chromium_importer/Cargo.toml.orig	2025-11-18 13:14:37 UTC
+++ apps/desktop/desktop_native/chromium_importer/Cargo.toml
@@ -45,7 +45,7 @@ verifysign = "=0.2.4"
 ] }
 verifysign = "=0.2.4"
 
-[target.'cfg(target_os = "linux")'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 oo7 = { workspace = true }
 
 [lints]
